server:
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: tomcat
    key-password: password
  port: 8443
spring:
  profiles:
    active: dev
google:
  client:
    url: "https://www.googleapis.com/oauth2"
    token: "https://oauth2.googleapis.com/token"